### ISSUE TITLE
ConvertRasterFormat Geotif to dep/flt

### ISSUE THREAD

**Issue by basaks** [jblindsay/whitebox-geospatial-analysis-tools#42]
I was trying to convert the tif I can download from here: http://download.osgeo.org/geotiff/samples/usgs/i30dem.tif

I could not get it to work with the following error.

```
whitebox_tools:$ gdalinfo i30dem.tif 
Driver: GTiff/GeoTIFF
Files: i30dem.tif
Size is 1479, 1863
Coordinate System is:
PROJCS["NAD27 / UTM zone 10N",
    GEOGCS["NAD27",
        DATUM["North_American_Datum_1927",
            SPHEROID["Clarke 1866",6378206.4,294.9786982138982,
                AUTHORITY["EPSG","7008"]],
            AUTHORITY["EPSG","6267"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4267"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-123],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","26710"]]
Origin = (532935.129999523167498,4205684.820000000298023)
Pixel Size = (30.000000000000000,-30.000000000000000)
Metadata:
  AREA_OR_POINT=Point
  TIFFTAG_DATETIME=1996:11:21 16:13:00
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=VICAR Program VTIFF
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  532935.130, 4205684.820) (122d37'29.58"W, 38d 0' 0.30"N)
Lower Left  (  532935.130, 4149794.820) (122d37'38.70"W, 37d29'46.78"N)
Upper Right (  577305.130, 4205684.820) (122d 7'10.44"W, 37d59'50.58"N)
Lower Right (  577305.130, 4149794.820) (122d 7'31.85"W, 37d29'37.25"N)
Center      (  555120.130, 4177739.820) (122d22'27.66"W, 37d44'49.72"N)
Band 1 Block=1479x1 Type=Int16, ColorInterp=Gray
whitebox_tools:$ ./whitebox_tools -r=ConvertRasterFormat -i i30dem.tif -o test.dep
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/libcollections/vec.rs:1422
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Same error when I attempt to convert to `.flt`
```
whitebox_tools:$ ./whitebox_tools -r=ConvertRasterFormat -i i30dem.tif -o test.flt
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/libcollections/vec.rs:1422
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is on ubuntu 16.04.

On the same box I could get the `MaxElevationDeviation` working:
```
./whitebox_tools -r=MaxElevationDeviation -v --dem=/home/ubuntu/dem_multiscale/dem_multiscale/oz_dem.dep -out_mag=/home/ubuntu/dem_multiscale/DEVmax_mag1.dep --out_scale=/home/ubuntu/dem_multiscale/DEVmax_scale1.dep --min_scale=3 --max_scale=99 --step=1
```

I was given the `.dep` in this case that was converted from `.tif` on windows.

**Comment by jblindsay** [comment]
Hello,
Thank you for this fantastic error report. The fact that this was so detailed and provided the data allowed me to test the situation. I think what is happening here is that you aren't using the 'cd' flag to tell WhiteboxTools what directory your data is contained within. I was able to convert you file with the following statement:

./whitebox_tools -r=ConvertRasterFormat --cd='/Users/johnlindsay/Downloads/' -i='i30dem.tif' -o='test.flt'

I'm also using the '=' with flags here. I'll check and see if I can find why leaving them out raises errors.

**Comment by basaks** [comment]
Thanks @jblindsay . I can confirm that `./whitebox_tools -r=ConvertRasterFormat --cd=$PWD --input='i30dem.tif' --output='test.dep'` worked for me. 

The command did not work without the `cd/wd` option, i.e, providing the direct path to the input file did not work with the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:859
```

**Comment by jblindsay** [comment]
I just committed code that will allow flags to be input using spaces rather than equal signs, e.g. --flag 'value' rather than --flag=value.
